on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

    # Sequence of patterns matched against refs/tags
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id:  tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token ${{ secrets.GITHUB_TOKEN}}
